### PR TITLE
"Rewrite" of some modules

### PR DESCRIPTION
**Pull request by lolleko**
Rewrote config
Rewrote curves
Rewrote Misc
Removed access to modules via an alias since it wasn’t used anywhere.

### CODE REVIEW

**Comment by Zet0rz** [comment]
We can remove the aliases sure, but then we'll need to use the nz\* tables rather than just *. We run too high of a risk of losing the tables permanently due to being overwritten, especially on common names such as Config or EE (which is why I stuck with nzEE with no alias).

**Comment by lolleko** [comment]
An alias won't fix that overwrite problem tho lol. I haven't had one conflict and i have 500+ add ons installed, but go ahead and change the animus if you feel like it.

**Comment by Zet0rz** [comment]
We don't necessarily need aliases, but they would be able to recover them should they get overwritten. But it's probably better to just use nz\* tables everywhere, so nzRound, nzDoors (the non-alias ones).

**Comment by lolleko** [comment]
No because the alias would get overwritten (gamemodes load before addons) and the reference to the table would be lost. Yeah change the name if you feel like it, imo its not needed. I mean we cam still overwrite them if we find any conflicts, right now there arent any.

**Comment by lolleko** [comment]
Renamed all modules to have a nz prefix, so it should be pretty unlikely that another addon overwrites the tables.

**Pull request merged**
