### PR TITLE
Make the scoreboard great again!

### PR DESCRIPTION
**Pull request by lolleko**
Added Points, Kills, Downs, Revives counts to the scoreboard.
Added Player colors to the scoreboard.
Added scoring system.
Improved overall design.

### CODE REVIEW

**Comment by lolleko** [comment]
Screenshot:
Screenshot

**Comment by Alig96** [comment]
Could you also fix the text of the top menu, bugs me that ready is so big and they're not aligned

**Comment by lolleko** [comment]
I think it's OS related on windows everything is aligned fine. I created this screenshot on unix, or maybe its just a font thing. I will look into it next.

**Comment by Alig96** [comment]
I meant the F1 menu, unrelated to the scoreboard. However the scoreboard is nice.

**Comment by lolleko** [comment]
Yeah i know, do you mean this particular screenshot or the f1 menu in general?

**Comment by Alig96** [comment]
F1 menu in general, its how it displays for me aswell.

**Pull request merged**
