### PR TITLE
Zombie water

### PR DESCRIPTION
**Pull request by lolleko**
Added ZombieWaterLevel() function as alternative to Gmod's Waterlevel() function
to the zombie base.

### CODE REVIEW

**Comment by func-octo** [comment]
Is this so that the zombies know the waterlevel?

**Comment by Alig96** [comment]
Reading the code, I assume so yes. The water level function returns 1,2,3 based on how deep the water is on the zombie.

1 is above the feet to the center,
2 is above the center to the top
3 is completely submerged

That's if I read it correctly

**Comment by func-octo** [comment]
How about adding bloated zombies? If you've ever played Plague inc., they're the ones that swim across oceans to infect other nations, but for this reason, it will make it easier to make configs for maps with water. Just keep the model (at least) above water level so they don't have to 'swim', but just float towards you.

**Comment by Zet0rz** [comment]
@ScriptnLua This function was only added because Nextbots cannot swim in gmod as of yet.

**Comment by lolleko** [comment]
Correct it's basically a recreation of the default gmod ENT:WaterLevel() function, the default one was broken / buggy on nextbots. And about the bloating thing, It's simply not possible to make floating zombies in the current gmod version. It's not implemented yet and you can't hard code it with (setpos/gravity) because that would bug out their locomotion engine. (I hope we get swimming functionality soon).

--snip--

**Comment by minin43** [comment]
Nextbots just need to be better. Honestly.

**Comment by Alig96** [comment]
Is it possible to make the next bots jump with the water? Surely if they're constanlty jumping they'll raise to the top?

**Comment by lolleko** [comment]
@minin43 Nextbots are really good, they have swimming climbing and all that stuff implemented in the engine but we don't have access to it in gmod :angry:.
@Alig96 I haven't tried that yet. But I think self.loco:Jump() requires the bot to stand on solid ground or at least some surface. I will give it a shot tho, would be amazing if this works.

**Pull request merged**
