### PR TITLE
Some Minor Fixes & Decapitation

### PR DESCRIPTION
**Pull request by lolleko**
Some Minor Zombie Fixes
Decapitation for zombie ragdolls

### CODE REVIEW

**Comment by func-octo** [comment]
> Decapitation for zombie ragdolls

Lovely.

**Comment by lolleko** [comment]
Just realised zombies have a orange something in there head, which doesn't disappear. No idea to which bone that belongs tho.

**Comment by Zet0rz** [comment]
The eyes maybe?

**Comment by lolleko** [comment]
But there is no "Eye Bone" or is there?

**Comment by Zet0rz** [comment]
Not too sure, it might be weight painted to something else. I'll have to try and check for that in Maya, or maybe try and individually apply it on all other bones and see which one does the trick? Maybe neck?

**Comment by func-octo** [comment]
You can study all bones in source filmmaker. I believe that there are bones for the eyes, but if not, just remove the eyes (somehow) after decapitation.

**Comment by lolleko** [comment]
Yeah the "somehow" is the difficult part, but i haven't spend much time looking for ways yet.

**Pull request merged**
