### PR TITLE
Black Ops 3 Styled HUD

### PR DESCRIPTION
**Pull request by ghost**
So I was reading through one of the projects and saw an idea from Dj_Nathan that said "perks near rounds like BO3?"
I commented on that (albeit nobody replied since it was like a month old or something) and posted example screenshots.

This here is the actual code I changed for my personal use.

CHANGES:
Round tallies only go up to five, changing to a number at 6 and beyond. This is done because the tally marks would overlap the perk icons, looking bad.

Perks are shown near the round, just like in BO3.

NOTES:
If you buy too many perks, (like 11 or more) then the icons will overlap with the text for power-ups. Shouldn't be a problem with the default perk limit of 4, and can go up to 10 without visual annoyance.

EXAMPLES:
https://gyazo.com/ad97916d7bbe25255eee915ada3eaf28

https://gyazo.com/b9af091282cf7b10778e1acf3366ac87

https://gyazo.com/a5ac01904b6d5719695b8ef073f8c79b

https://gyazo.com/14fc216e839f06e0294af7e11051fc45
(full screenshot, ignore the different font and Origins HUD, that's for my personal use.)

### CODE REVIEW

**Comment by minin43** [comment]
Is there more to the BO3 zombies HUD? Or is the icons change it?

**Comment by ghost** [comment]
@minin43 

This is the part of the BO3 zombies HUD that just changes the round number and the perk icon placement.

The other part of the HUD changes the notification on your screen when you can buy something.

EXAMPLE:

Normally it would say "Press E to buy Mystery Box for 950 points."

After modifying the code, now it says "Press E to use Mystery Box (Cost: 950)"
The same goes for weapons off the wall, perk machines, and buying ammo of the wall.

It's also farther below the cross-hair so it's less visually intruding. Here's a screenshot:

https://gyazo.com/7137e8171f9f693bc5c2d2eef78de9db
Ignore the leveling bar at the top, it was from a server content pack for nZombies.

NOTES:
Those perk icons are custom, I downloaded them from somewhere.

**Comment by Zet0rz** [comment]
I don't think I'm gonna switch to the BO3 HUD style unless I can animate the round indicators to "burn in" the same way as they do in BO3. I also want to keep the perk icons in their "minimal/cartoon" style, so I'm not gonna replace them with the ones seen in your screenshot.

**Comment by ghost** [comment]
@Zet0rz 

okay, but about the perk icons
those are clientside, you can keep the ones that come with the game-mode by default.

**Comment by NicoNicoNiiiiiiiiiiiiiiiiiiiii** [comment]
Can i download it?

**Pull request closed without merging**
