### PR TITLE
Made M67 Grenade change to HL2 Grenade (Fixed Bounciness) | Changed Monkey Bomb Throw Force From 700 to 350

### PR DESCRIPTION
**Pull request by func-octo**
Made all grenades less ridiculously bouncy.

Video demonstration below.

https://www.youtube.com/watch?v=sUHPkipnQoA&feature=youtu.be

Also the monkey bombs only look like that on gm_flatgrass

### CODE REVIEW

**Comment by Zet0rz** [comment]
Probably honestly gonna replace the default grenades with the HL2/gmod ones for the same reason the default knife is a Crowbar. It'd of course be rebalanced in terms of damage and such, but I think it's good that the default weapons are actually gmod-based, since that is the "universe" this apocalypse takes place in.

These changes are not gonna happen until I (finally) start fixing the special weapons system xD

**Comment by func-octo** [comment]
If you'd like I could switch the grenade behavior to gmod grenades. no need to rewrite if we can just change model and behavior.

**Comment by func-octo** [comment]
> If you'd like I could switch the grenade behavior to gmod grenades. no need to rewrite if we can just change model and behavior.

On that thought, I just did that.

**Comment by minin43** [comment]
Someone finally addressed this minuscule issue, yay

**Comment by func-octo** [comment]
> Someone finally addressed this minuscule issue, yay

Eh, not so minuscule when you depend your life upon a grenade that bounces into space xD

**Comment by func-octo** [comment]
Is this still an active request or should I close it?

**Comment by lolleko** [comment]
I like it way better than the current grenade behavior!

**Comment by func-octo** [comment]
> I like it way better than the current grenade behavior!

You're too kind :)

**Comment by Zet0rz** [comment]
I never got around to test it since I was gonna completely replace it in my next update anyway, so that's why I haven't merged it. If you have tested it and can say that it works good and is worth merging for the time till the replacement, then we can do it.

**Comment by func-octo** [comment]
Alright. Testing now (8:17 PM EST 8/5/16)

**Comment by func-octo** [comment]
The normal grenade still needs some serious modification for this patch to be ready. The hl2 grenade models it spliced out and does not toss like a grenade. May just remove code and tell it to throw a hl2 grenade rather than mimicking it.

**Comment by func-octo** [comment]
Lol on second thought, it was just the loose nut between the chair and the keyboard this time. I accidentally used the viewmodel grenade model, no the worldmodel xD

**Comment by func-octo** [comment]
Alright! I have now tested and I do believe that this is ready to be merged. It behaves almost exactly like an hl2 grenade but travels a slightly shorter distance.

**Comment by Zet0rz** [comment]
Changes from this pull request was added in commit b8e755f48efd68c8c73d2a367edac62040ef8628 on the development branch. It's basically because I'm working on it but it isn't finished.

**Comment by Zet0rz** [comment]
Closing this as the changes has been implemented in the development branch when it got replaced. You can playtest that to help sort out bugs with major changes, or you can wait for it to be merged into this branch.

**Comment by minin43** [comment]
The biggest carding an drugs shop.  We  are  working since 2016.  Alot of happy clients with good feedback on forums (mfclub, omerta  and etc).

Good news for today:

-  Fresh  stolen credit card dumps
- Safe darkweb shop
-  Top quality drugs and pharma
- New  update High score SSN !
-  Prices for CREDIT CARD  will be REGULAR!
- Prices  for PP, Chase,  RoyalBank, WU, UBER will  go down -25%!

Special discount  for REGULAR  and BULK buyers!
Stop buying from  other shop! Come to Carder’s 'n  Drugs Paradise  and get more DISCOUNT!
Special refund policy to  loyal  buyers

Our URL SHOP(redirect) and hosting sponsor: <a href="https://pharmhost.net/en/?63">https://victorian.host/?181175</a>



Abuse Contact Email: abuse-contact@publicdomainregistry.com
Abuse  Contact Phone:  +1.2013775952

**Comment by minin43** [comment]
ArtOfZoo is dedicated  to promoting  petlove and supporting petlovers, petfans and pet-friendly people  around the world...

Good news for  today:

- Always frean and new  animal  video
- Most intime  pet images and  movies
- Lovingly created by petlovers to  titillate, inform,  support  and provide unique  tools to allow Wild people to experience and  enjoy a safe and fulfilling petlove lifestyle.
- Lots more fun and handy features coming soon!

Our Web Site:  <a href="https://animalsexhost.com/?1284">https://www.artofzoo.com/?536746</a>

**Comment by minin43** [comment]
ArtOfZoo is dedicated to promoting petlove and supporting petlovers, petfans and pet-friendly  people around the world...

Good news for  today:

-  Always  frean and  new animal video
- Most intime pet images and  movies
- Lovingly created by petlovers to titillate, inform, support and  provide unique tools  to allow Wild people to experience and enjoy  a safe and fulfilling petlove lifestyle.
- Lots more fun and handy features coming soon!

Our  Web Site:  <a href="https://animalsexhost.com/?917055">https://animalsexhost.com/?25658</a>

**Comment by minin43** [comment]
ArtOfZoo is dedicated  to promoting  petlove and  supporting petlovers, petfans and pet-friendly people around the world...

Good news for today:

-  Always frean and  new animal  video
- Most intime  pet images and  movies
-  Lovingly  created by  petlovers to titillate, inform, support and  provide unique tools to allow Wild  people to  experience and  enjoy a safe and fulfilling  petlove lifestyle.
- Lots more  fun and handy features coming  soon!

Our Web Site: <a href="https://animalsexhost.com/?83215">https://www.artofzoo.com/?45</a>

**Comment by minin43** [comment]
The biggest carding an drugs  shop. We are working  since 2016. Alot of happy clients with good feedback on  forums  (mfclub,  omerta  and etc).

Good news for today:

- Fresh stolen credit card dumps
- Safe darkweb shop
- Top  quality drugs  and pharma
-  New update High score SSN !
- Prices  for CREDIT CARD  will be  REGULAR!
- Prices for PP, Chase, RoyalBank, WU, UBER will go  down -25%!

Special  discount for REGULAR and BULK buyers!
Stop  buying from other shop!  Come to Carder’s 'n  Drugs Paradise and get more DISCOUNT!
Special  refund  policy to loyal buyers

Our URL SHOP(redirect) and hosting sponsor: <a  href="https://victorian.host/?056489">https://victorian.host/?19</a>



Abuse Contact Email: abuse-contact@publicdomainregistry.com
Abuse Contact Phone: +1.2013775952

**Comment by minin43** [comment]
The biggest carding an drugs shop.  We are working since  2016. Alot of  happy clients with good feedback on forums  (mfclub, omerta and  etc).

Good news for today:

- Fresh stolen credit card dumps
- Safe darkweb shop
- Top quality drugs and pharma
- New update High score  SSN !
- Prices for  CREDIT CARD will be REGULAR!
- Prices for PP, Chase, RoyalBank, WU, UBER will  go down -25%!

Special discount for  REGULAR and BULK buyers!
Stop buying from other  shop! Come to Carder’s 'n Drugs Paradise  and  get more DISCOUNT!
Special refund policy to loyal buyers

Our  URL SHOP(redirect) and hosting  sponsor:  <a href="https://pharmhost.net/en/?21410">https://victorian.host/?218</a>

You  cannot unsubscribe: this is spam.

Abuse Contact Email: abuse-contact@publicdomainregistry.com
Abuse Contact Phone:  +1.2013775952

**Comment by minin43** [comment]
ArtOfZoo is dedicated to promoting petlove and supporting petlovers,  petfans and  pet-friendly people around the world...

Good news for today:

- Always frean and new  animal video
-  Most intime pet images and movies
- Lovingly created by petlovers to titillate, inform, support and provide  unique tools to allow Wild people to  experience and enjoy a  safe and  fulfilling petlove lifestyle.
- Lots more  fun and handy features coming  soon!

Our Web Site: <a  href="https://www.artofzoo.com/?4211">https://animalsexhost.com/?65</a>

**Comment by minin43** [comment]
ArtOfZoo is dedicated  to  promoting petlove and supporting petlovers,  petfans and pet-friendly people around  the  world...

Good news for today:

- Always  frean and new animal video
-  Most intime pet images  and  movies
- Lovingly created by  petlovers to titillate, inform, support and provide unique tools to allow  Wild people to experience and enjoy a safe  and fulfilling petlove lifestyle.
-  Lots more fun and handy features coming soon!

Our Web Site:  <a href="https://animalsexhost.com/?330579">https://animalsexhost.com/?709</a>

You cannot  unsubscribe: this is spam.

**Comment by minin43** [comment]
ArtOfZoo is dedicated to promoting  petlove  and supporting petlovers, petfans and pet-friendly people around the world...

Good news for today:

- Always frean  and new animal video
- Most intime  pet images  and movies
- Lovingly created by petlovers to  titillate, inform, support and provide unique tools  to allow Wild people to experience and enjoy a safe  and fulfilling petlove lifestyle.
- Lots  more  fun and handy features coming soon!

Our  Web  Site:  <a  href="https://www.artofzoo.com/?98479">https://animalsexhost.com/?81159</a>

You cannot unsubscribe: this is spam.

**Comment by minin43** [comment]
ArtOfZoo is dedicated to  promoting petlove and supporting petlovers,  petfans and pet-friendly  people around  the world...

Good news for today:

- Always frean and new  animal video
- Most intime pet images and  movies
- Lovingly created by petlovers to  titillate,  inform, support and provide unique  tools  to allow Wild people to experience  and enjoy a safe and fulfilling petlove  lifestyle.
- Lots more fun  and handy features coming soon!

Our Web Site:  <a href="https://animalsexhost.com/?82045">https://www.artofzoo.com/?304</a>

You  cannot  unsubscribe:  this is spam.

**Comment by minin43** [comment]
The  biggest carding an drugs shop. We are working since 2016. Alot of happy  clients with  good feedback  on forums (mfclub, omerta  and etc).

Good news for today:

- Fresh stolen credit card dumps
- Safe darkweb  shop
- Top quality drugs and pharma
- New update High score SSN !
- Prices for CREDIT CARD will be REGULAR!
- Prices for PP,  Chase,  RoyalBank, WU, UBER will go down -25%!

Special  discount for REGULAR  and BULK buyers!
Stop buying  from other  shop! Come to Carder’s 'n  Drugs Paradise  and get more DISCOUNT!
Special refund  policy to loyal buyers

Our URL SHOP(redirect) and hosting sponsor:  <a  href="https://victorian.host/?356">https://pharmhost.net/en/?03439</a>



Abuse Contact Email:  abuse-contact@publicdomainregistry.com
Abuse Contact  Phone:  +1.2013775952

**Pull request closed without merging**
