### PR TITLE
I have an idea!

### PR DESCRIPTION
**Pull request by func-octo**
It would be nice to have access to older versions, so I thought i would ask if you could make a release (release tab on code tab) every time you think that a commit is major enough. That would help people who don't know much about GitHub. This would let them just pick a release so that you can keep updating until you make another release a certain number of commits later.

P.S. It would also help my friends because reinstalling it every couple of days gets tedious...

Thanks!,
     ScriptnLua

### CODE REVIEW

**Comment by lolleko** [comment]
Thank you! But we already know how to upload add ons to the garrys mod workshop! @Zet0rz did not upload this addon yet is because it's not done  ( and not 100% in a stable state). As soon its stable and all unimplemented features are added this will be uploaded to the  garrys mod steam workshop.

**Comment by ScriptnLua** [comment]
Ok! I can see what you mean by that.
Also, a quick list of unplayable bugs:
Host can access wallbuys, perks, and randomboxes while players of the host's server cannot. (Even if they too have the gamemode as the latest version.)
Fonts missing on players screen as well as gui even if they have the gamemode on and selected it before joining (Any ideas here?)

**Comment by Zet0rz** [comment]
Fonts and gui elements should be in the addon file itself, check if they have it in [addon]/materials. Make sure they didn't install the "master" branch, but rather the "Master-Changes" one. It wasn't the default before (is now though).

Also what's the errors on not being able to access wall_buys and stuff? Just not buying it or ...? It works on my end when playtesting with my friends.

**Comment by ScriptnLua** [comment]
So I host a gmod server with nzombies running, map config, everything set up. I can use randomboxes by pressing e (gui shows up in right font), but my brother sees the default gmod font with the same message and he can't use them or wall buys or barricades, or anything interactive for that matter (he has enough points, something must be corrupted on his end, fastdl is not installed)

**Comment by ScriptnLua** [comment]
Also I was wondering if I could show this to the world for alpha testing, or beta, or whatever state it's in. Is that ok or should I wait until it's done?

**Comment by Zet0rz** [comment]
No problem recording and uploading, it isn't under any NDA :P

**Pull request closed without merging**
