### PR TITLE
Make the zombies jump again!

### PR DESCRIPTION
**Pull request by lolleko**
Added back zombie nav awareness
Added another stuck condition.

See https://github.com/Zet0rz/nzombies/wiki/Advanced-Navmesh-Editing#jumping for information on nav triggered jumping.

### CODE REVIEW

**Comment by minin43** [comment]
> -Added back zombie nav awareness

What does this mean?

**Comment by lolleko** [comment]
My bad should be "nav jump awareness" see the linked wiki entry for infos on that.

**Comment by minin43** [comment]
What's the command for adding this while editing?

**Comment by lolleko** [comment]
look at a nav area and type nav_jump in the console.

**Comment by Zet0rz** [comment]
We should probably make a nav editor tool in the list similar to Robotboys.

**Comment by minin43** [comment]
@lolleko Thanks

@Zet0rz If I could I would. If I could have helped in a lot more areas I would have, been I'm too inexperienced to be of assistance. Better to be left to the "professionals."

**Comment by lolleko** [comment]
You can go into sandbox and use this tool https://steamcommunity.com/sharedfiles/filedetails/?id=527885257. It makes nav editing a lot easier. Also here is the [Command reference](https://developer.valvesoftware.com/wiki/Navigation_Mesh_Commands) for all nav related console commands.

**Comment by Zet0rz** [comment]
> You can go into sandbox and use this tool https://steamcommunity.com/sharedfiles/filedetails/?id=527885257

That's the one I thought of remaking in nZombies (sort of).

**Comment by lolleko** [comment]
Yeah but why recreate it if its already there. At least right now we should focus on the other stuff first.

**Comment by minin43** [comment]
Yea, you can use a tool outside of the gamemode. But that isn't very helpful. I need to see where the props are so I can trace around them. I can't see the props if I'm not in the gamemode.

**Comment by lolleko** [comment]
Mhhh right. You can also bind the most important nav commands to keys. I mention a lot of editing techniques in my guide for guess who nav's, the guide is a bit outdated and not for this game mode (http://steamcommunity.com/sharedfiles/filedetails/?id=485737805). But almost everything applies to the zombies aswell, it may help you to improve the mesh so the zombies won't get stuck that often. I will update the wiki here soon.

**Comment by Alig96** [comment]
I highly suggest making a tool, literally all the tool Robotboy does is call thr console commands when clicked

**Comment by Zet0rz** [comment]
Noted in #121

**Pull request merged**
