### PR TITLE
nZombies Icon (The real one)

### PR DESCRIPTION
**Pull request by func-octo**
Here is the link for the icon. I'll try to get that error message to you, but I have school from 7 to 3:30. Also any better way to contact you? Gmail?

[Link Deleted]

### CODE REVIEW

**Comment by func-octo** [comment]
P.S. I added a wiki page on using the PaP..

**Comment by Zet0rz** [comment]
You can add me on steam to talk. And I'm not sure about that icon, I don't think we can use swasticas as an official icon. I was just gonna go for a bloody Z, possibly nZ if there's space for it. But you can add me to discuss

**Comment by func-octo** [comment]
Ok. I just made that one because I assumed 'n' meant Nazi Zombies, so, yeah. Not supporting them.

**Comment by func-octo** [comment]
icon24

If you see this, this is my first attempt at an official icon (it has to be named icon24.png even though it's 32x32)

**Pull request closed without merging**
