### PR TITLE
some fix

### PR DESCRIPTION
**Pull request by bozoweed**
hi i have fix the revie system ( #541  FIXED)
reset scorboad when reset game after lose

### CODE REVIEW

**Comment by DjNathann** [comment]
No codes?

**Comment by bozoweed** [comment]
they have codes look in files changed

**Comment by Punkinator7** [comment]
definitely put this one in master.

**Comment by DjNathann** [comment]
Have you tested it?

**Comment by lolleko** [comment]
@Zet0rz

**Comment by bozoweed** [comment]
thanks you for merge my change in your project :) i will go to make more fix in futur juste need time beetwin my work and my favorite time kill ( coding ) ^^ 

and i'm learn the lua for gmod by work on it ,so i go make better update in futur i think 

ps : sorry for my bad english i'm french

**Comment by sh4d0w59** [comment]
Nice fix my dude.  👍

**Comment by bozoweed** [comment]
thanks

**Pull request merged**
