### PR TITLE
Hook Calls

### PR DESCRIPTION
**Pull request by minin43**
I don't entirely know how to create a pull request for ONLY the files/changes I want, so I'm sticking with this for now and hoping you can cherry pick which parts you'll implement.

This pretty much just adds in a variety of hooks, mainly for personal use (I'm doing some unique voice stuff that requires this), but also for the benefit of other should they choose to do something similar or something with a map script.

If I fucked something up, which I probably did, then let me know.

### CODE REVIEW

**Comment by lolleko** [comment]
Pull request structure looks fine with me, I also like the hooks you added. But you should probably remove the map script (and custom pap names) from the pull.

**Comment by minin43** [comment]
@lolleko Please tell me how, I still don't fully understand how GitHub works.

**Comment by lolleko** [comment]
Revert the changes locally: That means restoring the pap names to the ones  in this repo and deleting the map script. Than sync your changes with github.

If you want to keep a copy of your changes before you revert, i suggest you create a new branch before reverting.

**Comment by minin43** [comment]
@lolleko I've actually got a few more hooks I need implement, then I'll throw the merge request back up

**Comment by lolleko** [comment]
Also check out this interactive site for git basics: https://try.github.io/

**Comment by Zet0rz** [comment]
I want to make hooks able to change things, e.g. the random box hook to return what weapon it is going to be, but the hook able to overwrite it by returning a different value. Same with Wunderfizz Perks, perks in general, and so on.

**Comment by minin43** [comment]
@Zet0rz Usually there is a "GetVariable" hook/function (for important variables) and a "SetVariable" hook/function.

I don't need to change anything, I only need to get the variables. I don't know how high/low this is on your priority, but at least this bare-bones functionality should be implemented _for now._ Go ahead and edit it later but I'm using these for my voices, I'm just adding these onto a commit merge because others might benefit.

**Comment by Zet0rz** [comment]
Check if you can use any of the hooks in commit 1d19e292f4f048e718b41917d4a69221bee1e525. There's two for getting and losing perks, as one is called before it checks whether the player even has the perk at all and before any other check, the other is only called after the perk was succesfully gotten/removed after all relevant checks. The earlier hooks can be used to prevent the perk from being acquired or removed entirely, and can then manually give a perk instead, while the latter are called _after_ perks have changed.

It also adds hooks for Wunderfizz and Box which, like the earlier hooks here, can have a string returned which will then overwrite what outcome it becomes.

**Comment by Zet0rz** [comment]
Powerups and easter egg hooks in this commit 8e67e9fbfe9cc0f9684103f50d60c1a414292e92

**Comment by minin43** [comment]
Here is a full-detailed list of hooks I need (some of which DO NOT need to be included in the gamemode, they're already in gmod's library)
-Ammo low
-Ammo out
-Crawler spawned
-Crawler damaged
-Crawler killed (I know crawlers aren't in- this is all eventual)
-Player damaged
-Dog/Special round begin (MUST be able to distinguish the two)
-Dog killed
-Song unlocked (also need player who activated the final egg)
-Insufficient funds (pressing E on mystery box/wall buy/doorway without the required amount of points)
-All perks (also need the caller)
-Game start
-All powerups (as well as the person who picked it up)
-Revive (both on down and on up)
-Mystery Box teddy spawn (also need caller for this as well)
-Bowie knife purchase
-Monkey bomb received in Mystery box
-General weapon purchases (either from the wall or from the mystery box - along with caller for each)
-Zombie death (in close proximity to player)
-Zombie death (after being hit by them)
-Zombie death (via explosion)
-Zombie death (via flame/fire)
-Zombie death (during insta-kill)
-Zombie death (if player is on a kill-streak)
Zombie death (via multi-kill from grenade)

**Comment by Zet0rz** [comment]
> -Ammo low
> -Ammo out

You'll need to use an EntityFireBullets hook for these, manually checking when ammo is low (there are no hooks that check this for you). Alternatively, intercept SetAmmo function to call your stuff on top of setting ammo.

> -Player damaged

Already exists (EntityTakeDamage, check if ent is a player)

> -Dog/Special round begin (MUST be able to distinguish the two)

Use the OnRoundStart and check if nzRound:IsSpecial(). You can check if it's a dog round the same way the code does it to say "Fetch me their souls"

> -Dog killed

EntityTakeDamage, check if damage is over health, check if ent is a dog. Alternatively, I think there's already a ZombieDeath hook or something like that, if not then I'll make it

> -Song unlocked (also need player who activated the final egg)
> -All powerups (as well as the person who picked it up)
> -All perks (also need the caller)
> -Mystery Box teddy spawn (also need caller for this as well)
> -Monkey bomb received in Mystery box (Just use mystery box hook and see what the outcome was)

Added

> -Monkey bomb received in Mystery box (Just use mystery box hook and see what the outcome was)
> -Bowie knife purchase

Alternatively use a WeaponEquip hook

> -Insufficient funds (pressing E on mystery box/wall buy/doorway without the required amount of points)
> -General weapon purchases (either from the wall or from the mystery box - along with caller for each)
> -Bowie knife purchase

I'll have to make a CanBuy hook that runs every time any price transaction is attempted

> -Zombie death (in close proximity to player)
> -Zombie death (after being hit by them)
> -Zombie death (via explosion)
> -Zombie death (via flame/fire)
> -Zombie death (during insta-kill)
> -Zombie death (if player is on a kill-streak)
> Zombie death (via multi-kill from grenade)

Same as dog. Use various checks on the damage info for who and what damaged them, perform own checks for instakill, and own logic for kill streaks.

> -Revive (both on down and on up)
> -Game start

Exists

**Comment by minin43** [comment]
I know most of them you don't need to do anything for, I just wanted to make a giant list of everything, so you at least know. Thanks though

**Comment by Zet0rz** [comment]
I have changed how buying stuff works internally in a major way. Instead of doing something like

``` Lua
if ply:CanAfford(200) then
    -- Stuff
   ply:TakePoints(200)
end
```

they are now all called like this:

``` Lua
ply:Buy(200, entity, function()
    -- Stuff
end)
```

This includes calling the hook OnPlayerBuy in which you can return a new price or return true to completely prevent the buy and the function from running. If the function is run and it returned true (internal success check), it will call OnPlayerBought hook. Added in commit 3008445d841bae8a9892ab67768540eacb15190b.
[You can see the function here](https://github.com/Zet0rz/nzombies/blob/3008445d841bae8a9892ab67768540eacb15190b/gamemodes/nzombies/gamemode/points/sh_points.lua#L57).

**Comment by Zet0rz** [comment]
I also edited the Available Hooks page to have a few of our hooks and look a similar way to the official gmod wiki. Not all hooks have been added yet, especially not any of the development branch ones.

**Comment by minin43** [comment]
Thanks!

**Comment by minin43** [comment]
Some questions:
-Can I get a PlayerIsDown function that returns true/false if the given player is or is not down? I didn't see one in the code but maybe I just passed it
-This one is kinda stupid but it's never been explained to me, when I hook onto something that starts with GM: or NEXTBOT:, do I need to include those prefixes in the hook.Add?
-Do NEXTBOTs count as NPCs?
-What is the "range of the melee or "+use" key? I've got dialogue that is based on how close the zombie is and I want it to work at either melee or "+use" range, but I don't know either.

**Comment by Zet0rz** [comment]
player:GetNotDown() returns true if the player is alive. 

Hooks with hook.Add do not need the prefix. Also, I'm not sure anything other than GM: ones work with hook.Add, the rest are for usage in entity files (such as SWEP:PrimaryAttack())

I'm not entirely sure, never experimented with it really. 

The range of use is defined in the FindUseEntity hook. Melee range is just coded into the melee weapons themselves.

**Comment by minin43** [comment]
> Also, I'm not sure anything other than GM: ones work with hook.Add, the rest are for usage in entity files (such as SWEP:PrimaryAttack())

You may need to add a hook in for NEXTBOT death. Since there isn't a player one for NPC/NEXTBOT kill (only player death that returns both the attacker and victim), and I need a way to track the kills players are getting (as well as the NEXTBOT's CTakeDamageInfo and NEXTBOT entity itself). This will need to be unique per NEXTBOT type (dog, normal zombie, special zombie, panzer, etc)

**Comment by Zet0rz** [comment]
If there isn't a ZombieKilled hook, I'll make one. Otherwise, you can use EntityTakeDamage where you get can attacker from the dmginfo. It's how we already run kill logic (giving points etc).

**Comment by minin43** [comment]
Yea but I want to avoid having to do dumb checks like "is zombiehealth <= 1" and things like that. Things that could otherwise be done on a ZombeKilled hook

**Pull request closed without merging**
